version: '3'

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    # To access on ip
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "51:80/tcp"
      - "953:433/tcp"
#      - "53:53"
#      - "51:80"
    expose:
      - "51"
    environment:
      #      - PUID=1000
      #      - PGID=1000
      - TZ=Europe/Amsterdam
      - WEBPASSWORD=1989PiholeCAB0607!
        #      - DNS1=127.0.0.1
        #      - DNS2=1.1.1.1
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(\"pihole.dynadex.dev\")"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"

networks:
  web:
    external: true
