version: '2'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    volumes: 
      - /home/coen/docker/traefik/traefik.yaml:/traefik.yaml:ro
      - /home/coen/docker/traefik/acme/acme.json:/acme.json
      - /home/coen/docker/traefik/rules:/rules:ro
      - /home/coen/docker/traefik/transip.key:/transip.key:ro
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - 80:80
      - 443:443
      # To access on ip
      - 3518:8080
    expose:
      - "3518"
    environment:
      - TRANSIP_ACCOUNT_NAME=dynadex
      - TRANSIP_PRIVATE_KEY_PATH=transip.key
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(\"traefik.dynadex.dev\")"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

networks:
  web:
    external: true

