http:
  routers:
    hass:
      entryPoints:
        - https
      service: hass
      rule: Host("home.dynadex.dev")
      middlewares:
        - "hsts"
      tls: {}

  services:
    hass:
      loadBalancer:
        servers:
          - url: http://192.168.2.2:2875
        passHostHeader: true
